name: NTop CI

# Trigger on every master branch push and pull request
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Run Build
      run: cmake --build .
